# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
    end
    config.vm.box = "ubuntu/trusty64"
    config.vm.network "private_network", ip: "192.168.33.13"
    config.vm.synced_folder "../../../", "/var/www/steam_projects/"

    config.vm.provision :shell, path: "install-node.sh", privileged: false
    config.vm.provision :shell, path: "install-apache.sh", privileged: false
end
